### ISSUE TITLE
Oakland Use of Force section - add plots and UoF level descriptions to tabs

### ISSUE THREAD

**Issue by whitneyseiler** [sfbrigade/datasci-police-budget#283]
- PR to tab between UoF levels: https://github.com/sfbrigade/datasci-police-budget/pull/280/files
 - different plots per level: 
   - PNG files here: https://github.com/sfbrigade/datasci-police-budget/tree/master/oaklanddataset/graph
   - data here: https://github.com/sfbrigade/datasci-police-budget/tree/master/oaklanddataset/data
 - different descriptions per level: can be found in the links here: https://www.oaklandca.gov/resources/use-of-force

**Comment by carmodydr** [comment]
PR to add level descriptions: https://github.com/sfbrigade/datasci-police-budget/pull/303
